'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});
var RNS_SHOW_NOTIFICATION = 'RNS_SHOW_NOTIFICATION';
exports.RNS_SHOW_NOTIFICATION = RNS_SHOW_NOTIFICATION;
var RNS_HIDE_NOTIFICATION = 'RNS_HIDE_NOTIFICATION';
exports.RNS_HIDE_NOTIFICATION = RNS_HIDE_NOTIFICATION;